config/routes.rb
Rails.application.routes.draw do
  root to: "game_rooms#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :messages
  resources :room_players
  resources :players
  resources :game_rooms do
    resources :game_elements, only: [:create, :update, :destroy]
    get 'play'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/room_player.rb
class RoomPlayer < ApplicationRecord
  belongs_to :player
  belongs_to :game_room
end

app/controllers/room_players_controller.rb
class RoomPlayersController < ApplicationController
  before_action :set_room_player, only: %i[ show edit update destroy ]

  # GET /room_players or /room_players.json
  def index
    @room_players = RoomPlayer.all
  end

  # GET /room_players/1 or /room_players/1.json
  def show
  end

  # GET /room_players/new
  def new
    @room_player = RoomPlayer.new
  end

  # GET /room_players/1/edit
  def edit
  end

  # POST /room_players or /room_players.json
  def create
    @room_player = RoomPlayer.new(room_player_params)

    respond_to do |format|
      if @room_player.save
        format.html { redirect_to room_player_url(@room_player), notice: "Room player was successfully created." }
        format.json { render :show, status: :created, location: @room_player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @room_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_players/1 or /room_players/1.json
  def update
    respond_to do |format|
      if @room_player.update(room_player_params)
        format.html { redirect_to room_player_url(@room_player), notice: "Room player was successfully updated." }
        format.json { render :show, status: :ok, location: @room_player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @room_player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_players/1 or /room_players/1.json
  def destroy
    @room_player.destroy

    respond_to do |format|
      format.html { redirect_to room_players_url, notice: "Room player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_player
      @room_player = RoomPlayer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_player_params
      params.require(:room_player).permit(:player_id, :game_room_id, :morale, :energy)
    end
end

app/views/room_players/_form.html.erb
<%= form_with(model: room_player) do |form| %>
  <% if room_player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(room_player.errors.count, "error") %> prohibited this room_player from being saved:</h2>

      <ul>
        <% room_player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :player_id, style: "display: block" %>
    <%= form.text_field :player_id %>
  </div>

  <div>
    <%= form.label :game_room_id, style: "display: block" %>
    <%= form.text_field :game_room_id %>
  </div>

  <div>
    <%= form.label :morale, style: "display: block" %>
    <%= form.number_field :morale %>
  </div>

  <div>
    <%= form.label :energy, style: "display: block" %>
    <%= form.number_field :energy %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/room_players/_room_player.html.erb
<div class="row player" id="<%= dom_id room_player %>">
  <div class="col player-user" style="color: <%= room_player.player.color %>">
    <%= room_player.player.username %>
  </div>
  <div class="col player-status">
    <%= room_player.status == 1 ? "Online" : "Offline" %>
  </div>
  <div class="col player-morale">
    <%= room_player.morale %>
  </div>
  <div class="col player-energy">
    <%= room_player.energy %>
  </div>
</div>

app/views/room_players/edit.html.erb
<h1>Editing room player</h1>

<%= render "form", room_player: @room_player %>

<br>

<div>
  <%= link_to "Show this room player", @room_player %> |
  <%= link_to "Back to room players", room_players_path %>
</div>

app/views/room_players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Room players</h1>

<div id="room_players">
  <% @room_players.each do |room_player| %>
    <%= render room_player %>
    <p>
      <%= link_to "Show this room player", room_player %>
    </p>
  <% end %>
</div>

<%= link_to "New room player", new_room_player_path %>

app/views/room_players/new.html.erb
<h1>New room player</h1>

<%= render "form", room_player: @room_player %>

<br>

<div>
  <%= link_to "Back to room players", room_players_path %>
</div>

app/views/room_players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @room_player %>

<div>
  <%= link_to "Edit this room player", edit_room_player_path(@room_player) %> |
  <%= link_to "Back to room players", room_players_path %>

  <%= button_to "Destroy this room player", @room_player, method: :delete %>
</div>