config/routes.rb
Rails.application.routes.draw do
  root to: "game_rooms#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :messages
  resources :room_players
  resources :players
  resources :game_rooms do
    resources :game_elements, only: [:create, :update, :destroy]
    get 'play'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/game_room.rb
class GameRoom < ApplicationRecord
  has_many :room_players, dependent: :destroy
	has_many :players, through: :room_players
	has_many :game_elements, dependent: :destroy

	validates :map_terrain, presence: true
	validates :map_width, presence: true
	validates :map_width, numericality: {greater_than_or_equal_to: 3}

	validate :check_squared_map
	validate :check_map_height

	def check_squared_map
		return unless (map_width && map_terrain)
		errors.add(:map_terrain, "Map Terrain is not squared") unless map_terrain.length % map_width == 0
	end

	def check_map_height
		errors.add(:map_terrain, "Map Terrain should be at least 3 tiles tall") unless map_terrain.length / map_width >= 3
	end

	# Probably should also validate that the map is sourrounded all by walls
	# Would need to know which characters are walls, the user will only set up this later.
	# Should add a boolean, map_is_playable or walls_verified
	# This boolean would be change on update and will tell the user if the map is valid to play.

end

app/controllers/game_rooms_controller.rb
class GameRoomsController < ApplicationController
  before_action :set_game_room, only: %i[ show edit update destroy ]

  # GET /game_rooms or /game_rooms.json
  def index
    @game_rooms = GameRoom.all
  end

  # GET /game_rooms/1 or /game_rooms/1.json
  def show
    setup_elements
  end

  # GET /game_rooms/new
  def new
    @game_room = GameRoom.new(map_width: 5, map_terrain: "WWWWWWOOOWWOOOWWWWWW")
  end

  # GET /game_rooms/1/edit
  def edit
    @element = @game_room.game_elements.build
  end

  # GET /game_rooms/1/edit
  def play
    @game_room = GameRoom.find(params[:game_room_id])
    setup_elements
  end

  # POST /game_rooms or /game_rooms.json
  def create
    @game_room = GameRoom.new(game_room_params)

    respond_to do |format|
      if @game_room.save
        format.html { redirect_to game_room_url(@game_room), notice: "Game room was successfully created." }
        format.json { render :show, status: :created, location: @game_room }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /game_rooms/1 or /game_rooms/1.json
  def update
    respond_to do |format|
      if @game_room.update(game_room_params)
        elements = @game_room.game_elements.map{ |elem| {element: elem, image_path: elem.image.present? ? rails_blob_path(elem.image, only_path: true) : nil } }
        GameChannel.broadcast_to(@game_room, { game: @game_room, elements: elements, players: @game_room.players });
        format.html { redirect_to edit_game_room_path(@game_room), notice: "Game room was successfully updated." }
        format.json { render :show, status: :ok, location: @game_room }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game_room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /game_rooms/1 or /game_rooms/1.json
  def destroy
    @game_room.destroy

    respond_to do |format|
      format.html { redirect_to game_rooms_url, notice: "Game room was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    def setup_elements
      @elements = {}
      @game_room.game_elements.order(updated_at: :desc).each do |elem|
        if not elem.persisted?
          next
        elsif not @elements[elem.key_code]
          @elements[elem.key_code] = [];
        end
        @elements[elem.key_code].push(elem);
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_game_room
      @game_room = GameRoom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def game_room_params
      params.require(:game_room).permit(:map_terrain, :map_width)
    end
end

app/views/game_rooms/_elements_cubes.html.erb
<div class="table">
  <div class="row">
    <div class="col justify-center">Key Code</div>
    <div class="col justify-center">Elements</div>
    <div class="col justify-center lg-col">Images</div>
  </div>
  <% elements_collection.each do |key_code, elements| %>
    <div class="row">
      <div class="col justify-center">
        <%= key_code %>
      </div>
      <div class="col justify-center">
        <% elements.each do |elem| %>
          <%= elem.element_type %><br>
        <% end %>
      </div>
        <div class="col justify-center lg-col">
          <div class="animated-cube">
            <div class="cube <%= (elements.first && elements.first.element_type.downcase.include?('wall')) ? "horizontal" : "vertical"%>">
              <% elements.each do |elem| %>
                <% if elem.image.present? %>
                  <% if elem.element_type.downcase == "walln" %>
                    <div class="cube-face cube-face-north" style="background-image: url(<%= url_for(elem.image) %>);">north</div>
                  <% elsif elem.element_type.downcase == "walls" %>
                    <div class="cube-face cube-face-south" style="background-image: url(<%= url_for(elem.image) %>);">south</div>
                  <% elsif elem.element_type.downcase == "wallw" %>
                    <div class="cube-face cube-face-west" style="background-image: url(<%= url_for(elem.image) %>);">west</div>
                  <% elsif elem.element_type.downcase == "walle" %>
                    <div class="cube-face cube-face-east" style="background-image: url(<%= url_for(elem.image) %>);">east</div>
                  <% elsif elem.element_type.downcase == "floor" %>
                    <div class="cube-face cube-face-floor" style="background-image: url(<%= url_for(elem.image) %>);">floor</div>
                  <% elsif elem.element_type.downcase == "ceiling" %>
                    <div class="cube-face cube-face-ceiling" style="background-image: url(<%= url_for(elem.image) %>);">ceiling</div>
                  <% end %>
                <% end %>
              <% end %>
              <% if (elements.filter{|elem| elem.element_type.downcase == "walln"}).empty? %>
                <div class="cube-face cube-face-north">north</div>
              <% end %>
              <% if (elements.filter{|elem| elem.element_type.downcase == "walls"}).empty? %>
                <div class="cube-face cube-face-south">south</div>
              <% end %>
              <% if (elements.filter{|elem| elem.element_type.downcase == "walle"}).empty? %>
                <div class="cube-face cube-face-east">east</div>
              <% end %>
              <% if (elements.filter{|elem| elem.element_type.downcase == "wallw"}).empty? %>
                <div class="cube-face cube-face-west">west</div>
              <% end %>
              <% if (elements.filter{|elem| elem.element_type.downcase == "floor"}).empty? %>
                <div class="cube-face cube-face-floor">floor</div>
              <% end %>
              <% if (elements.filter{|elem| elem.element_type.downcase == "ceiling"}).empty? %>
                <div class="cube-face cube-face-ceiling">ceiling</div>
              <% end %>
            </div>
          </div>
          <% elements.each do |elem| %>
          <% end %>
        </div>
    </div>
  <% end %>
</div>

app/views/game_rooms/_form.html.erb
<%= form_with(model: game_room) do |form| %>
  <% if game_room.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game_room.errors.count, "error") %> prohibited this game_room from being saved:</h2>

      <ul>
        <% game_room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div 
    data-controller="map-editor"
  >

    <div id="mapInfo"></div>

    <div id="mapEditor" data-action="keydown->map-editor#updateEditables"></div>

    <button data-action="click->map-editor#addColumn">Add Column</button>
    <button data-action="click->map-editor#removeColumn">Remove Column</button>
    <button data-action="click->map-editor#addRow">Add Row</button>
    <button data-action="click->map-editor#removeRow">Remove Row</button>

    <hr>

    <details>
      <summary>Show Raw Inputs</summary>
      <div>
        <%= form.label :map_terrain, style: "display: block" %>
        <%= form.text_area :map_terrain, {"data-action": "change->map-editor#onTextChange", "data-map-editor-target": "inputMap" }%>
      </div>
      <div>
        <%= form.label :map_width, style: "display: block" %>
        <%= form.number_field :map_width, {"data-map-editor-target": "inputWidth", "data-action": "change->map-editor#onWidthChange" }%>
      </div>
    </details>

    <hr>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/game_rooms/edit.html.erb
<p style="color: green"><%= notice %></p>
<p style="color: red">
  <% if not alert.nil? and alert.any? %>
    <div style="color: red">
      <h4><%= pluralize(alert.count, "error") %> prohibited this game element from being saved:</h4>

      <ul>
        <% alert.each do |error| %>
          <li><%= error[0] %>: <span style="color: darkred;"><%= error[1] %></span></li>
        <% end %>
      </ul>
    </div>
  <% end %>    
</p>
<div class="center">
  <h1>Editing game room</h1>

  <%= render "form", game_room: @game_room %>

  <br>

<div class="table">
  <div class="row">
    <div class="col">
      Create Elements to customize your Map
    </div>
    <div class="col">
      Walls, Background, Ceiling, Floor
    </div>
  </div>
  <div class="row">
    <div class="col">
       <%= form_with(model: [@game_room, @element], html: {class: 'float-left mr-1'}) do |form| %>
        <%= form.hidden_field :element_type, value: 'wallN' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          Wall_N
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <%= form_with(model: [@game_room, @element], html: {class: 'float-left mr-1'}) do |form| %>
        <%= form.hidden_field :element_type, value: 'wallS' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          Wall_S
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <%= form_with(model: [@game_room, @element], html: {class: 'float-left mr-1'}) do |form| %>
        <%= form.hidden_field :element_type, value: 'wallE' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          Wall_E
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <%= form_with(model: [@game_room, @element], html: {class: 'float-left mr-1'}) do |form| %>
        <%= form.hidden_field :element_type, value: 'wallW' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          Wall_W
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <%= form_with(model: [@game_room, @element], html: {class: 'float-left mr-1'}) do |form| %>
        <%= form.hidden_field :element_type, value: 'floor' %>
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          Floor
        <% end %>
      <% end %>
    </div>
    <div class="col">
      <%= form_with(model: [@game_room, @element], html: {class: 'float-left mr-1'}) do |form| %>
        <%= form.hidden_field :element_type, value: 'ceiling' %> 
        <%= button_tag(type: 'submit', class: 'btn btn-secondary') do %>
          Ceiling
        <% end %>
      <% end %>
    </div>
  </div>
  <% @game_room.game_elements.order(updated_at: :desc).each do |elem| %>
    <% if elem.persisted? %>
      <%= form_with(model: [@game_room, elem]) do |form| %>
        <div class="row">
            <div class="col">
              <%= elem.element_type %>
            </div>
            <div class="col">
              <%= form.text_field :key_code, maxlength: 1 %>
            </div>
            <div class="col">
               <% if elem.image.present? %>
                  <%= image_tag(elem.image, width: "125px") %>
                <% else %>
                  No image Present
                <% end %>
                <%= form.file_field :image %>
            </div>
            <div class="col">
              <%= form.submit "Save", class: 'btn btn-primary'%>
              <%= link_to 'Delete', game_room_game_element_path(@game_room, elem), class: 'delete-btn', data: {turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this element?"} %>
            </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

  <div>
    <%= link_to "Show this game room", @game_room %> |
    <%= link_to "Back to game rooms", game_rooms_path %>
  </div>
</div>

app/views/game_rooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="center">Game rooms</h1>

<div id="game_rooms" class="table_container">
  <% @game_rooms.each do |game_room| %>
    <div class="table">
      <%= link_to game_room do %>
        <h3> Room # <%= game_room.id %></h3>
        <svg
          data-controller="map-viewer"
          data-map-viewer-width-value="<%=game_room.map_width%>"
          data-map-viewer-map-value="<%= game_room.map_terrain %>"
        />
      <% end %>      
    </div>
  <% end %>
</div>

<h2 class="center"><%= link_to "New game room", new_game_room_path %></h2>

app/views/game_rooms/new.html.erb
<div class="center">
<h1>New game room</h1>

<%= render "form", game_room: @game_room %>

<br>

<div>
  <%= link_to "Back to game rooms", game_rooms_path %>
</div>
</div>

app/views/game_rooms/play.html.erb
<div class="table_container">
	<div class="table">
		<div class="row">
			<div class="col">
				<div class="row no-outilne">
					<div class="col no-outilne">
						<h1>Room # <%= @game_room.id %></h1>
						<svg
							data-controller="map-viewer"
							data-map-viewer-width-value="<%=@game_room.map_width%>"
							data-map-viewer-map-value="<%= @game_room.map_terrain %>"
							id="map-viewer-svg"
						/>
					</div>
				</div>
				<div class="row">
					<div 
						data-controller="game"
						class="col no-outilne" style="width: 100%"
						data-game-game-id-value="<%=@game_room.id%>"
					>
						<button
							class="play_button"
							data-action="click->game#load_game"
						>Play</button>
					</div>
				</div>
			</div>
			<div class="col">
				<h2>Players</h2>
				<div id="room-players-table" class="room-players-table">
					<% if @game_room.room_players.any? %>
						<div class="row">
							<div class="col no-outilne">username</div>
							<div class="col no-outilne">status</div>
							<div class="col no-outilne">morale</div>
							<div class="col no-outilne">energy</div>
						</div>
			      <%= render @game_room.room_players %>
			    <% end %>
				</div>
				<div class="col">
					<div class="no-outilne">W - Walk Forwards</div>
					<div>S - Walk Backwards</div>
					<div>A - Turn Left</div>
					<div>D - Turn Right</div>
					<div>E - Fly Up</div>
					<div>C - Crouch Down</div>
					<div>Q - Look Up</div>
					<div>Z - Look Down</div>
					<div>M - Show Map</div>
					<div>Shift - Run</div>
				</div>
			</div>
		</div>
	</div>
</div>

<div class="center container">
	<div id="canvas_container" class="canvas-frame">
	</div>
	<div id="thisId"></div>
</div>

app/views/game_rooms/show.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "Back to game rooms", game_rooms_path %>
<div class="row" id="<%= dom_id @game_room %>">
  <div class="col">
      <strong>Map terrain:</strong>
      <svg
        data-controller="map-viewer"
        data-map-viewer-width-value="<%=@game_room.map_width%>"
        data-map-viewer-map-value="<%= @game_room.map_terrain %>"
      />
  </div>
  <div class="col">
    <strong>Map width:</strong>
    <p>
      <%= @game_room.map_width %>
    </p>
  </div>
  <div class="col">
    <%= link_to "Edit this game room", edit_game_room_path(@game_room) %>
    <%= link_to "Play this game room", game_room_play_path(@game_room) %>
    <%= button_to "Destroy this game room", @game_room, method: :delete %>
  </div>
</div>

<%= render "elements_cubes", elements_collection: @elements %>