config/routes.rb
Rails.application.routes.draw do
  root to: "game_rooms#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :messages
  resources :room_players
  resources :players
  resources :game_rooms do
    resources :game_elements, only: [:create, :update, :destroy]
    get 'play'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/player.rb
class Player < ApplicationRecord
	has_many :messages, dependent: :destroy
  has_many :room_players, dependent: :destroy
  has_many :game_rooms, through: :room_players
  NAME_REGEX = /\w+/
  validates :username, presence: true, uniqueness: { case_sensitive: false },
                       format: { with: /\A#{NAME_REGEX}\z/i },
                       length: { maximum: 15 }
  validates :password, presence: true, length: { minimum: 6 }
  has_secure_password
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    @players = Player.all
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        helpers.log_in @player
        format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :bio, :color, :username, :password, :password_confirmation)
    end
end

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :bio, style: "display: block" %>
    <%= form.text_field :bio %>
  </div>

  <div>
    <%= form.label :color, style: "display: block" %>
    <%= form.text_field :color %>
  </div>

  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>
  
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation, "Confirmation" %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <strong>Name:</strong>
    <%= player.name %>
  </p>

  <p>
    <strong>Username:</strong>
    <%= player.username %>
  </p>

  <p>
    <strong>Bio:</strong>
    <%= player.bio %>
  </p>

  <p>
    <strong>Color:</strong>
    <%= player.color %>
  </p>

</div>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="center">Players</h1>

<div id="players" class="table_container">
  <% @players.each do |player| %>
    <div class="table">
      <%= link_to player do %>
        <%= render player %>
      <% end %>
    </div>
  <% end %>
</div>

<h2 class="center"><%= link_to "New player", new_player_path %></h2>

app/views/players/new.html.erb
<div class="dialog">
  <h1>Sign up</h1>

  <%= render "form", player: @player %>

  <ul class="session-links">
    <li>Already have an account?</li>
    <li><%= link_to "Sign In", login_path %></li>
    <li><%= link_to "Back to players", players_path %></li>
  </ul>
</div>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "Back to players", players_path %>

<div class="row" id="<%= dom_id @player %>">

  <div class="col">
    <strong>Name:</strong>
    <%= @player.name %>
  </div>

  <div class="col">
    <strong>Bio:</strong>
    <%= @player.bio %>
  </div>

  <div class="col">
    <strong>Color:</strong>
    <%= @player.color %>
  </div>

  <div class="col">
    <%= link_to "Edit this player", edit_player_path(@player) %>
    <%= button_to "Destroy this player", @player, method: :delete %>
  </div>

</div>