config/routes.rb
Rails.application.routes.draw do
  root to: "game_rooms#index"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :messages
  resources :room_players
  resources :players
  resources :game_rooms do
    resources :game_elements, only: [:create, :update, :destroy]
    get 'play'
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RayCastingGame</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="session_navbar">
    <% if logged_in? %>
      <div>
        <%= link_to edit_player_path(current_player) do %>
          <svg version="1.1" id="_x32_" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 512 512" xml:space="preserve" fill="#ffffff" transform="matrix(1, 0, 0, 1, 0, 0)" stroke="#ffffff"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <style type="text/css"> .st0{fill:#3d3846;} </style> <g> <path class="st0" d="M441.594,101.713H70.406c-38.812,0-70.398,31.586-70.406,70.411v167.753 c0.008,38.815,31.594,70.401,70.406,70.41h371.188c38.812-0.009,70.397-31.595,70.406-70.41V172.124 C511.991,133.299,480.406,101.713,441.594,101.713z M441.594,384.455H70.406c-11.898,0-23.1-4.637-31.532-13.046 c-8.414-8.438-13.051-19.629-13.06-31.532V172.124c0.009-11.894,4.646-23.096,13.056-31.532 c8.436-8.419,19.638-13.056,31.536-13.056h371.188c11.898,0,23.1,4.637,31.532,13.046c8.414,8.445,13.051,19.647,13.06,31.541 v167.753c-0.009,11.903-4.646,23.094-13.056,31.522C464.694,379.818,453.492,384.455,441.594,384.455z"></path> <rect x="152.748" y="175.752" class="st0" width="215.131" height="159.811"></rect> <polygon class="st0" points="95.546,212.633 71.649,212.633 71.649,243.714 40.567,243.714 40.567,267.611 71.649,267.611 71.649,298.692 95.546,298.692 95.546,267.611 126.627,267.611 126.627,243.714 95.546,243.714 "></polygon> <path class="st0" d="M453.92,211.102c-10.183,0-18.44,8.248-18.44,18.44c0,10.174,8.257,18.44,18.44,18.44 c10.184,0,18.44-8.266,18.44-18.44C472.36,219.35,464.104,211.102,453.92,211.102z"></path> <path class="st0" d="M412.43,263.343c-10.184,0-18.44,8.248-18.44,18.44c0,10.174,8.256,18.44,18.44,18.44 c10.184,0,18.44-8.266,18.44-18.44C430.87,271.59,422.614,263.343,412.43,263.343z"></path> </g> </g></svg>
        <% end %>
      </div>
      <div>
        <%= link_to logout_path, data: { "turbo-method": :delete } do %>
          <svg width="64px" height="64px" viewBox="0 0 25.00 25.00" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#c01c28" stroke-width="0.55"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M11.75 9.874C11.75 10.2882 12.0858 10.624 12.5 10.624C12.9142 10.624 13.25 10.2882 13.25 9.874H11.75ZM13.25 4C13.25 3.58579 12.9142 3.25 12.5 3.25C12.0858 3.25 11.75 3.58579 11.75 4H13.25ZM9.81082 6.66156C10.1878 6.48991 10.3542 6.04515 10.1826 5.66818C10.0109 5.29121 9.56615 5.12478 9.18918 5.29644L9.81082 6.66156ZM5.5 12.16L4.7499 12.1561L4.75005 12.1687L5.5 12.16ZM12.5 19L12.5086 18.25C12.5029 18.25 12.4971 18.25 12.4914 18.25L12.5 19ZM19.5 12.16L20.2501 12.1687L20.25 12.1561L19.5 12.16ZM15.8108 5.29644C15.4338 5.12478 14.9891 5.29121 14.8174 5.66818C14.6458 6.04515 14.8122 6.48991 15.1892 6.66156L15.8108 5.29644ZM13.25 9.874V4H11.75V9.874H13.25ZM9.18918 5.29644C6.49843 6.52171 4.7655 9.19951 4.75001 12.1561L6.24999 12.1639C6.26242 9.79237 7.65246 7.6444 9.81082 6.66156L9.18918 5.29644ZM4.75005 12.1687C4.79935 16.4046 8.27278 19.7986 12.5086 19.75L12.4914 18.25C9.08384 18.2892 6.28961 15.5588 6.24995 12.1513L4.75005 12.1687ZM12.4914 19.75C16.7272 19.7986 20.2007 16.4046 20.2499 12.1687L18.7501 12.1513C18.7104 15.5588 15.9162 18.2892 12.5086 18.25L12.4914 19.75ZM20.25 12.1561C20.2345 9.19951 18.5016 6.52171 15.8108 5.29644L15.1892 6.66156C17.3475 7.6444 18.7376 9.79237 18.75 12.1639L20.25 12.1561Z" fill="#c01c28"></path> </g></svg>
        <% end %>
      </div>
    <% else %>
      <div>
        <%= link_to "Sign up", new_player_path %>
      </div>
      <div>
        <%= link_to "Login", login_path %>
      </div>
    <% end %>
    </div>
    <%= yield %>
  </body>
</html>